name: Deploy Windmill
on:
  # Manueel starte
  workflow_dispatch:

jobs:
  docker-compose:
    runs-on: 
        group: default
        labels: unraid
    environment: unraid
    steps:    
        - uses: actions/checkout@v3
        - name: Docker Compose Action
          uses: isbang/compose-action@v1.5.1
          with:
            compose-file: ./docker-compose.yml
            up-flags: "--dry-run"
            services: |
                db
                windmill_server
                windmill_worker
                windmill_worker_native
                lsp
  